site_name: om_midi_NGDXW_zh 中文文档
repo_url: https://github.com/Z4HD/om_midi_NGDXW_zh
copyright: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="知识共享许可协议" style="border-width:0;width: auto;" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />本<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" rel="dct:type">文档</span>采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可。<br /><i>仅文档受CC约束。om_midi_NGDXW_zh.jsx 仍然进入公有领域，不受CC约束。</i><br />原作：<i>(c) 2003-2013 <a href="//omino.com">omino.com</a></i>'

nav:
  - 首页: 'index.md'
  - '安装&运行': 'install.md'
  - 简单入门: 'tutorial.md'
  - 关键帧参考:
    - 'reference/index.md'
    - '音高(pitch)': 'reference/pitch.md'
    - '力度(vel)': 'reference/vel.md'
    - '持续时间(dur)': 'reference/dur.md'
    - 'reference/scale.md'
    - 'reference/adv-scale.md'
    - 'reference/rotation.md'
    - 'reference/count.md'
    - 'reference/bool.md'
    - 'reference/t.md'
  - 'credits.md'

theme:
  name: readthedocs
  highlightjs: true
  hljs_style: monokai-sublime

markdown_extensions:
  - admonition
  - nl2br
  - extra
plugins:
  - search

google_analytics: ['UA-108438517-3', 'om.z4hd.cf']